version: '3'

services:
  database:
    image: mysql:5.7.26
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=joel
      - MYSQL_PASSWORD=joel@mysql
      - MYSQL_ROOT_PASSWORD=joel@mysql
    volumes:
      - ./db:/var/lib/mysql
    expose:
      - "3306"

